trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o $(Build.ArtifactStagingDirectory)/filesystem.bin
        displayName: 'Build Go Project'

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'drop'  # Name of the artifact
          targetPath: $(Build.ArtifactStagingDirectory)
          publishLocation: 'Container'  # Publish to Azure DevOps artifacts container

  - job: deployToVM
    dependsOn: buildGoJob
    steps:
    # Download the published artifact
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        artifactName: 'drop'  # Name of the artifact you published
        targetPath: $(Pipeline.Workspace)/drop  # Location to download the artifact

    # Copy the artifact to the Azure Linux VM using SSH
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'testsshserviceconnection'  # Your SSH service connection name
        sourceFolder: '$(Build.ArtifactStagingDirectory)/drop'  # Path to the downloaded artifact folder
        contents: '**/*'  # Copy all files in the artifact
        targetFolder: '/home/laurisseau/filesystem/'  # The directory on the Azure Linux VM where you want to upload the file
        cleanTargetFolder: true  # Clean target folder before upload (optional)

    # Run the Linux-compatible executable on the VM
    - task: SSH@0
      inputs:
        sshEndpoint: 'testsshserviceconnection'  # Your SSH service connection name
        runOptions: 'inline'
        inline: |
          cd /home/laurisseau/filesystem  # Update with the directory where you deployed
          chmod +x filesystem.bin # Ensure the file is executable
          ./filesystem.bin # Run the Linux executable
        displayName: 'Run Executable on Linux VM'