trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Manually install Go version 1.18
- script: |
    sudo apt-get update
    sudo apt-get install -y golang-1.18-go
    export GOROOT=/usr/lib/go-1.18
    export GOPATH=$HOME/go
    export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
    go version
  displayName: 'Install Go 1.18'

- script: |
    go mod tidy
  displayName: 'Install dependencies and run tests'

- script: |
    go build -o $(Build.ArtifactStagingDirectory)/fileSystem .
  displayName: 'Build Go app'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path to the directory where the artifacts are located
    artifactName: 'drop'  # Artifact name for the build output
    publishLocation: 'Container'  # Publish location (Azure DevOps artifacts)
