trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o filesystem.exe
        displayName: 'Build Go Project'

    variables:
      azureSubscription: $(azureSubscription)  
      vmIPAddress: $(vmIPAddress)
      adminUsername: $(adminUsername)
      adminPassword: $(adminPassword) 

  - job: DeployToVM
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'testserviceconnection'
        scriptType: 'ps' 
        scriptLocation: inlineScript
        inlineScript: |
          Write-Host "Hello, World!"

    displayName: 'Deploy to Windows 10 VM'