trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o filesystem.exe
        displayName: 'Build Go Project'

    variables:
      azureSubscription: $(azureSubscription)  
      vmIPAddress: $(vmIPAddress)
      adminUsername: $(adminUsername)
      adminPassword: $(adminPassword) 

  - job: DeployToVM
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'testserviceconnection'
        scriptType: 'ps'  # Changed to PowerShell for better remoting support
        scriptLocation: inlineScript
        inlineScript: |
          # PowerShell remoting to the Windows VM
          $securePassword = ConvertTo-SecureString $(adminPassword) -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($(adminUsername), $securePassword)

    displayName: 'Deploy to Windows 10 VM'