trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y golang
  displayName: 'Install Go'

- script: |
    go version  # Check Go version to confirm installation
  displayName: 'Check Go Version'

- script: |
    go mod tidy
  displayName: 'Install dependencies and run tests'

- script: |
    go build -o $(Build.ArtifactStagingDirectory)/fileSystem .
  displayName: 'Build Go app'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path to the directory where the artifacts are located
    artifactName: 'drop'  # Artifact name for the build output
    publishLocation: 'Container'  # Publish location (Azure DevOps artifacts)
