trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o $(Build.ArtifactStagingDirectory)/filesystem.exe
        displayName: 'Build Go Project'

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'drop'  # Name of the artifact
          targetPath: $(Build.ArtifactStagingDirectory)
          publishLocation: 'Container'  # Publish to Azure DevOps artifacts container

  - job: deployToWindowsVM
    dependsOn: buildGoJob
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          artifactName: 'drop'
          targetPath: $(Pipeline.Workspace)/drop

      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: 'testsshserviceconnection'
          sourceFolder: '$(Pipeline.Workspace)/drop'
          contents: '**/*'
          targetFolder: 'C:/Users/laurisseau/filesystem'  # Make sure this folder exists or use an existing one
          cleanTargetFolder: true

      - task: SSH@0
        inputs:
          sshEndpoint: 'testsshserviceconnection'
          runOptions: 'inline'
          inline: |
            cd C:\Users\laurisseau\filesystem
            Start-Process filesystem.exe
          displayName: 'Run Executable'