trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o filesystem.exe
        displayName: 'Build Go Project'


  - job: deployJob
    dependsOn: buildGoJob
    steps:
      - task: SSH@0
        inputs:
          sshEndpoint: 'testsshserviceconnection'
          runOptions: 'inline'
          inline: |
            cd /home/laurisseau/filesystem/ 

            rm -f filesystem.exe  # Remove the old file if it exists
            
            mv filesystem.exe .  # Deploy new executable

            ./filesystem.exe  # Start the application or do any post-deploy tasks