trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o $(Build.ArtifactStagingDirectory)\filesystem.exe
        displayName: 'Build Go Project'

  - job: DeployToVM
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'testserviceconnection'
        scriptType: 'ps' 
        scriptLocation: inlineScript
        inlineScript: |
          az login --tenant ${env:tenantId}


    displayName: 'Deploy to Windows 10 VM'