trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o $(Build.ArtifactStagingDirectory)/filesystem.exe
        displayName: 'Build Go Project'

      - task: SSH@0
        inputs:
          sshEndpoint: 'testssh'
          runOptions: 'commands'
          commands: |
            mkdir -p ~/deploy
        displayName: 'Create directory on VM'

      - task: SSH@0
        inputs:
          sshEndpoint: 'testssh'
          runOptions: 'script'
          scriptPath: '$(Build.ArtifactStagingDirectory)/filesystem.exe'
          targetPath: '/home/your-username/deploy/filesystem.exe'  # Replace with the path you want on the VM
        displayName: 'Copy binary to VM'

      - task: SSH@0
        inputs:
          sshEndpoint: 'testssh'
          runOptions: 'commands'
          commands: |
            chmod +x ~/deploy/filesystem.exe
            nohup ~/deploy/filesystem.exe > ~/deploy/output.log 2>&1 &
        displayName: 'Run binary on VM'