trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o filesystem.exe
        displayName: 'Build Go Project'