trigger:
  - main

pool:
  name: 'testagentpool'

jobs:
  - job: buildGoJob
    steps:
      - task: GoTool@0
        inputs:
          version: '1.23.5'

      - script: go build -o $(Build.ArtifactStagingDirectory)\filesystem.exe
        displayName: 'Build Go Project'

    variables:
      azureSubscription: $(azureSubscription)  
      vmIPAddress: $(vmIPAddress)
      adminUsername: $(adminUsername)
      adminPassword: $(adminPassword) 

  - job: DeployToVM
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'testserviceconnection'
        scriptType: 'ps' 
        scriptLocation: inlineScript
        inlineScript: |
          # Set the path where you want to store the executable
          $sourcePath = "$(Build.ArtifactStagingDirectory)\filesystem.exe"
          $destinationDirectory = "C:\Program Files\filesystem"
          $destinationPath = "$destinationDirectory\filesystem.exe"

          # Check if the destination directory exists, if not, create it
          if (-not (Test-Path -Path $destinationDirectory)) {
              New-Item -Path $destinationDirectory -ItemType Directory
          }

          # Copy the executable to the destination
          Copy-Item -Path $sourcePath -Destination $destinationPath -Force
          
          # Confirm deployment
          Write-Host "Deployed filesystem.exe to $destinationPath"

          # Run the executable
          Write-Host "Running filesystem.exe..."
          Start-Process -FilePath $destinationPath -NoNewWindow -Wait
          
          Write-Host "Execution completed."

    displayName: 'Deploy to Windows 10 VM'